[package]
authors = ["Chainflip team <https://github.com/chainflip-io>"]
edition = '2021'
build = 'build.rs'
name = "chainflip-cli"
version = "0.10.0"

[dependencies]
anyhow = "1.0"
clap = { version = "3.2.16", features = ["derive", "env"] }
config = "0.13.1"
futures = "0.3.14"
hex = { version = "0.4.3", features = ["serde"] }
serde = { version = "1.0", features = ["derive", "rc"] }
tokio = { version = "1.13.1", features = ["full"] }
serde_json = "1.0"

# Local Deps
chainflip-engine = { path = "../../../engine/" }
chainflip-api = { path = "../../lib" }
cf-chains = { path = "../../../state-chain/chains" }
utilities = { path = "../../../utilities" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/chainflip-io/substrate.git", tag = 'chainflip-monthly-2023-08+2' }

[package.metadata.deb]
depends = "$auto, systemd"
extended-description = """\
Chainflip CLI"""
maintainer = "Chainflip Labs GmbH <dev@chainflip.io>"
name = "chainflip-cli"
priority = "required"
section = "rust"
[package.metadata.deb.variants.test]
assets = [["target/release/chainflip-cli", "usr/bin/", "755"]]

[package.metadata.deb.variants.sisyphos]
assets = [["target/release/chainflip-cli", "usr/bin/", "755"]]

[package.metadata.deb.variants.perseverance]
assets = [["target/release/chainflip-cli", "usr/bin/", "755"]]

[package.metadata.deb.variants.berghain]
assets = [["target/production/chainflip-cli", "usr/bin/", "755"]]