on:
  workflow_call:
    inputs:
      version:
        description: Release version
        required: true
        type: string

permissions:
  id-token: write
  contents: read
jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get branch of tag
        id: get_tag
        run: |
          echo "tag=$(./ci/scripts/extract_version.sh ${{ inputs.version }})" >> $GITHUB_OUTPUT

      - name: Download packages
        uses: actions/download-artifact@v3
        with:
          name: chainflip-backend-packages-ubuntu-22.04
          path: ${{ steps.get_tag.outputs.tag }}

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::771478732399:role/chainflip-github-bot

      - name: Upload packages to s3 pre-release bucket
        run: |
          aws s3 mv --recursive --include "*.deb" ${{ inputs.version }} s3://chainflip-mainnet-prerelease/